steps:
  # Step 1: Execute the Ansible playbook
  - name: 'gcr.io/cloud-builders/ansible:2.9.27'
    args:
      - '-i'
      - 'localhost,'
      - 'sample.yml'

  # Step 2: Run npm build (assuming it's intended, adjust if not)
  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'build']

  # Step 3: Run script on VM
  - name: run_script_on_vm
    entrypoint: sh
    args:
      - |-
        # Access resources using IAM permissions granted to the service account
        gcloud config set account [SERVICE_ACCOUNT_EMAIL]

options:
  logging: CLOUD_LOGGING_ONLY
  serviceAccount: '[testserviceaccount@ansible-project-413417.iam.gserviceaccount.com]'  # Replace with your service account email
# ... other options
