steps:
  # Step 1: Execute the Ansible playbook
  - name: 'gcr.io/cloud-builders/ansible'
    args:
      - '-i'
      - 'localhost,'
      - 'sample.yml'
    steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/my-project/my-image', '.']
    logsBucket: 'gs://ansible_demo_bucket001/logfolder'
