steps:
  # Step 1: Execute the Ansible playbook
  - name: 'gcr.io/cloud-builders/ansible'
    args:
      - '-i'
      - 'localhost,'
      - 'sample.yml'
  # Step 2: Run npm build (assuming it's intended, adjust if not)
  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'build']
  options:
    default_logs_bucket_behavior: REGIONAL_USER_OWNED_BUCKET


