steps:
  - name: 'sushantmangaonkar22/6e66e9b62fc3:test1'
    args:
      - '-i'
      - 'localhost,'
      - 'sample.yml'

  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'build']

  - name: run_script_on_vm
    entrypoint: sh
    args:
      - |-
        # Access resources using IAM permissions granted to the service account
        gcloud config set account [SERVICE_ACCOUNT_EMAIL]

serviceAccount: '[testserviceaccount@ansible-project-413417.iam.gserviceaccount.com]'  # Replace with your actual service account email

options:
  logging: CLOUD_LOGGING_ONLY
