steps:
  # Step 1: Execute the Ansible playbook
  - name: 'gcr.io/cloud-builders/ansible'
    args:
      - '-i'
      - 'localhost,'
      - 'sample.yml'
    steps:
    options:
    default_logs_bucket_behavior: REGIONAL_USER_OWNED_BUCKET

