steps:
  # Step 1: Execute the Ansible playbook
  - name: 'gcr.io/cloud-builders/ansible:2.9.27'
    args:
      - '-i'
      - 'localhost,'
      - 'sample.yml'

  # Step 2: Run npm build (assuming it's intended, adjust if not)
  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'build']

options:
  logging: CLOUD_LOGGING_ONLY




