---
- name: Print Sentence
  hosts: sample    #sample
  gather_facts: false
  connection: ssh
  become: true

  tasks:
    - name: Print a Sentence
      debug:
        msg: "Hello, this is a simple Ansible playbook!"
